### ISSUE TITLE
SMS bomber not working

### ISSUE THREAD

**Issue by rela589n** [bhattsameer/Bombers#10]
![Screenshot from 2019-06-22 19-07-03](https://user-images.githubusercontent.com/41589422/59966173-09a86100-9521-11e9-8bcf-54579593a6ce.png)

**Comment by bhattsameer** [comment]
Sorry for late reply, yeah the links are not working properly, there are two links which are working fine all are there in the code already, also some of them required headers so i have implemented whole code in python2 now, and the links which are working have some throttle implemented, so continues OTP or message sending not possible you have to adjust the sleep time according the throttle.  The new python2 code i will add, with name sms_bomber_updated.py
