### ISSUE TITLE
SMS_Bomber craches when launching.

### ISSUE THREAD

**Issue by Cottonwoodhill** [bhattsameer/Bombers#102]
unusable.
Win 10.
python installed.

**Comment by Cottonwoodhill** [comment]
SMS_bomber_version2 => don't sent any SMS.

**Comment by Cottonwoodhill** [comment]
SMS_bomber_updated doesn't start.

**Comment by bhattsameer** [comment]
Hello @Cottonwoodhill Thanks for the update I will update the status of those to not working for time being, We will see if it is resolved by merging new pull request which was raised.
