### ISSUE TITLE
Error when trying to use SMS bomber

### ISSUE THREAD

**Issue by G3ckoHacks** [bhattsameer/Bombers#103]
hello when starting up the program sms_bomber_updated.py i get this error
Traceback (most recent call last):
  File "/home/gecko/Desktop/Bombers/sms_bomber_updated.py", line 3, in <module>
    import urllib2,cookielib
ModuleNotFoundError: No module named 'urllib2'

![Screenshot_2022-04-02_22-18-37](https://user-images.githubusercontent.com/102857112/161380773-3c1cfd68-7690-45b1-b939-53d541816b63.png)

**Comment by donjuan355** [comment]
sorry for my bad English. put nano SMS_bomber.py
and delete line 4 " #from urllib.parse import urlencode "

**Comment by GrowingHacker** [comment]
me too

**Comment by Zday-X** [comment]
@G3ckoHacks 

**CAUSE OF ERROR** : The module that is **_producing the error_** is written in _**python v2**_ and the system has **_python v3._**

**REPLICATE THIS ERROR** : Run the module with **_python3_** installed in your system.

**FIX** : 
SOLUTION 1: Install python2 from [here](https://www.python.org/downloads/) and install required dependencies.

SOLUTION 2: Port the module which is written in python2 to python3. Instructions on how to do can be found [here](https://docs.python.org/3/howto/pyporting.html) [May not work necessarily].


Ill fork this repo and port the code manually to python3 along with adding efficiency to the code.

Check my github  for updates!

_**NOTE**_: _**The module is not assured to work even after porting them to python3 as it has many dead api.**_
