### ISSUE TITLE
module problem

### ISSUE THREAD

**Issue by GrowingHacker** [bhattsameer/Bombers#104]
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\1\Bombers\SMS_bomber.py", line 3, in <module>
    import urllib2,cookielib
ModuleNotFoundError: No module named 'urllib2'

what should i do for this

**Comment by Zday-X** [comment]
The issue Had already been opened and answered: https://github.com/bhattsameer/Bombers/issues/103#issue-1190602934
