### ISSUE TITLE
Error in wbomb.py

### ISSUE THREAD

**Issue by xoxo112** [bhattsameer/Bombers#107]
python3 wbomb.py
Traceback (most recent call last):
  File "/home/kali/Bombers/wbomb.py", line 3, in <module>
    from webdriver_manager.chrome import ChromeDriverManager  # 1st changer
ModuleNotFoundError: No module named 'webdriver_manager'

**Comment by Muhammad-Fiqri** [comment]
Try write this on the terminal (CMD).
`pip install webdriver_manager`
this code will install the needed module
