### ISSUE TITLE
Deprecation error

### ISSUE THREAD

**Issue by inglesuniversal** [bhattsameer/Bombers#109]
wbomb.py:17: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())  # 2nd change
Enter the name of user or group: NAME
Enter your message: Hello World
Enter the count: 1
Enter any key after scanning QR code
/python/Bombers/wbomb.py:26: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead

Any Suggestions?

Thanks

**Comment by bhattsameer** [comment]
Closing this as making this a read-only project now, if anyone wants to contribute please reach out.
