### ISSUE TITLE
XLR8_BOMBER doesn't exists

### ISSUE THREAD

**Issue by KirillMerz** [bhattsameer/Bombers#114]
![image](https://user-images.githubusercontent.com/62656177/183132033-43f2c000-48b6-46da-8f6b-7f5c66d9c9ae.png)

**Comment by Zday-X** [comment]
Well i forked the repository before its got wiped out. Check out my github repo.

**Comment by Zday-X** [comment]
> ![image](https://user-images.githubusercontent.com/62656177/183132033-43f2c000-48b6-46da-8f6b-7f5c66d9c9ae.png)

Well i forked the repository before its got wiped out. Check out my github repo.
