### ISSUE TITLE
Missing the modules and doesn't work at all

### ISSUE THREAD

**Issue by MigrantBirdd** [bhattsameer/Bombers#120]
hey guys;
all cmnd is missing the other modules and no req. or library file is in the package!
would anyone please guide to solve the issues?
tnx in advanced

**Comment by mrrobotnotfound** [comment]
Same Issue.. please help

**Comment by Ravanamalrk** [comment]
problem Parayda

**Comment by bhattsameer** [comment]
Closing!! As making this a read-only project now, if anyone wants to contribute please reach out.
