### ISSUE TITLE
Require OTP links for making sms bomber more efficient.

### ISSUE THREAD

**Issue by bhattsameer** [bhattsameer/Bombers#5]
In Sms_bomber and Sms_bomber2 the links which i have used some of them are not working. need more links or a api if available there so that we can make it more reliable.

**Comment by IceWreck** [comment]
Take a look at this:
https://www.snip2code.com/Snippet/3307638/BOMBitUP---OTP-apis-calls/

**Comment by bhattsameer** [comment]
Thank you so much. @IceWreck

**Comment by bhattsameer** [comment]
only two worked which i already have. @IceWreck

**Comment by IceWreck** [comment]
Which ones did? Did you check the post request ones?

**Comment by bhattsameer** [comment]
ya did checked post too, but because right the whole code is based on get request that's why i tried if i get more link with get request if available, other wise i should move from only get to get+post.

regarding get only only godaddy, naptol are working. which i already have.

**Comment by bhattsameer** [comment]
Sure, if you can help and collaborate that will also good, just fork the repo and push your commits.

**Comment by kushpvo** [comment]
I would have done that but I don't know how to grab the api url for the otp submission
That's why i suggested here to have a look

**Comment by bhattsameer** [comment]
ok, I will look into it, for the post we have to made so many changes in code, I will try to update the same. Thanks for the help.

**Comment by kushpvo** [comment]
Oh okay
And for POST, any url is okay? Or things like cookies and csrf matters to us?
Because I found some post links but they have csrf and cookies

**Comment by bhattsameer** [comment]
matters.

**Comment by bhattsameer** [comment]
Help in testing the mentioned links are working or not? I have created labels, green, blue and red.

**Comment by kushpvo** [comment]
@bhattsameer Sure, I can do that. I'll submit a PR after testing all the links.

**Comment by bhattsameer** [comment]
Some predeveloped Bomber scripts are available so I have mentioned them in repo, for managing all scripts out there for email/sms bombers, I have not tested all of them, so if you can it will be helpful, just mention, the labels related to working, not working or you found any issue in those. also you can mention another bomber script you found out there.

**Comment by bhattsameer** [comment]
> @bhattsameer Sure, I can do that. I'll submit a PR after testing all the links.

@kushpvo Thank you!

**Comment by iMro0t** [comment]
@kushpvo @bhattsameer  i added massive amount of links in my new commit almost 25 different sms providers that can make some one tired badly

**Comment by bhattsameer** [comment]
> @kushpvo @bhattsameer i added massive amount of links in my new commit almost 25 different sms providers that can make some one tired badly

Awesome, Thanks brother.

**Comment by iMro0t** [comment]
anyone can contribute this project by adding more links in 
https://github.com/iMro0t/bomb3r/blob/master/original.json

**Comment by bhattsameer** [comment]
https://github.com/Nikait/ni_bomber/blob/master/services.py For links.

**Comment by bhattsameer** [comment]
Closing this, as I am not able to make changes to the old python scripts actively and the motive of this repo is already diverted to a collection of available tools/ scripts from internet.
