### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by weechoochoo** [bhattsameer/Bombers#50]
I dont know how to use this

**Comment by timofey260** [comment]
use [exe file](https://github.com/timofey260/pyspam) and press at stroke for spam

**Comment by IND-PIYUSH** [comment]
Umm ... Can Run it in Linux If Yess.....
Can Tell Requirments + Cmnds  ? ;)

**Comment by timofey260** [comment]
### addons
import **codecs, pyautogui, os, time, colorama, pyperclip, keyboard**

### modes in menu:
1. 'mode' start spaming with modes
> 1. _file_: name of file and interval
>> **file.txt** (you need to use utf8 encoding)
>> `first stroke`
>> `second stroke`

> **script**
>> file: "file.txt":
>>> `first stroke`
>>> `second stroke`

> 2. _message_: message, repeat times and interval
>> message: "mes", repeat times: 3:
>>> `mes`
>>> `mes`
>>> `mes`

> 3. _num_message_: preffix, suffix, interval and repeat times: `suffix`current repeat`preffix`
>> preffix: "text1 ", suffix: "text2 ", repeat times: 3:
>>> `text1 1 text2`
>>> `text1 2 text2`
>>> `text1 3 text2`

2. 'credits' - credits
3. 'Errorlist' - list of errors
4. 'exit' - exit the programm
5. 'version' - version number: ver.ver.patch. current:"1.2.5"
6. 'log' - last updates

@IND-PIYUSH
