### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by hash30** [bhattsameer/Bombers#59]
I'm trying to run wbomb.py, but don't know which python version is used to run it as there are no instructions in README.md file, please update README.md file to show the users how to use all tools including this one i'm trying to use, and create a requirement.txt file to install all required dependencies for all py modules available in Bombers.
![wbomberror](https://user-images.githubusercontent.com/54507991/107607148-6a3c6280-6c5e-11eb-9a00-b14dc7370bc0.png)

**Comment by bhattsameer** [comment]
pip install selenium

**Comment by bhattsameer** [comment]
Use steps mentioned here: https://github.com/tbhaxor/whatabomb

**Comment by hash30** [comment]
> Use steps mentioned here: https://github.com/tbhaxor/whatabomb

With which python version do i use it?

**Comment by hash30** [comment]
i mean wbomb.py

**Comment by hash30** [comment]
What to do now? I've installed all required dependencies but can't figure how to add chrome driver to a path!
![wbomberror](https://user-images.githubusercontent.com/54507991/107613313-0cb01200-6c6e-11eb-8966-5cf35a4cad4b.png)

![cdriver](https://user-images.githubusercontent.com/54507991/107613338-1afe2e00-6c6e-11eb-957f-04fadffcfc68.png)

![chromebrowser](https://user-images.githubusercontent.com/54507991/107613355-24879600-6c6e-11eb-95cb-4bfcef777d2c.png)

**Comment by bhattsameer** [comment]
It  is in python2 actually. But not sure if it is still working or not. Apart from this you can try using GUI version of this: https://github.com/tbhaxor/whatabomb See if this will be helpful.
