### ISSUE TITLE
*on

### ISSUE THREAD

**Issue by timofey260** [bhattsameer/Bombers#63]
Edit description of pyspam, please

**Comment by bhattsameer** [comment]
Sure, it would be helpful if you share the proper description of pyspam with me. So i will add it: So far the repo itself I found it is a "Spam for pc."

**Comment by timofey260** [comment]
I meant to correct the word ok to on

**Comment by bhattsameer** [comment]
Oh Yeah, So silly mistake of mine. Thanks will update it. :))
