### ISSUE TITLE
Updated Email-Bomber Script

### ISSUE THREAD

**Issue by everydaycodings** [bhattsameer/Bombers#65]
# I have reprogrammed this code and Added Some Features:
**send email to multiple users and multiple time with this Email-Bomber**

***Repository Link:***
[https://github.com/everydaycodings/Email-Bomber](https://github.com/everydaycodings/Email-Bomber)

**Comment by gbstixx** [comment]
Does this work for gmail? for some reason after the first sent message, there's an error: STARTTLS extension not supported by server. how do I fix it?

**Comment by everydaycodings** [comment]
> Does this work for gmail? for some reason after the first sent message, there's an error: STARTTLS extension not supported by server. how do I fix it?

Ya i especially tried it on gmail and it worked all the time. By reading that error i see there is problem in your server or gmail settings please check your gmail settings or google it the problem.

**Comment by everydaycodings** [comment]
or you can try this code
Pull Request: https://github.com/bhattsameer/Bombers/pull/68
