### ISSUE TITLE
Email bomber

### ISSUE THREAD

**Issue by sw1pe** [bhattsameer/Bombers#7]
Something is wrong with input is displaying when putting in email in email bomber

**Comment by bhattsameer** [comment]
yes, i got some issue in it too, smtp.authentication error, i guess google now not allowed login without any non google app. i am looking into it. 
Thanks for raising this issue.

**Comment by bhattsameer** [comment]
Kindly user other email bombers I have added. https://github.com/bhattsameer/Bombers/blob/master/README.md
