### ISSUE TITLE
New Option of TBomb

### ISSUE THREAD

**Issue by 0n1cOn3** [bhattsameer/Bombers#77]
We've added Mail-Bombing in V2.3 
Please update the sheet :)

**Comment by bhattsameer** [comment]
Can you help me with a pull request? Else i will look into it and update accordingly. Thanks.

**Comment by bhattsameer** [comment]
@0n1cOn3 I have seen your https://github.com/TheSpeedX/TBomb Awesome work. This makes a new option of call bombing as well. I request you to please raise a pull request with all this links in to SMS bombing, mail bombing and Call bombing too.

**Comment by Eots91** [comment]
Not work

**Comment by 0n1cOn3** [comment]
> Can you help me with a pull request? Else i will look into it and update accordingly. Thanks.

Sure. Leme know what you need

**Comment by bhattsameer** [comment]
Done, Thanks and Cheers!!
