### ISSUE TITLE
These bombers are not working

### ISSUE THREAD

**Issue by anubhavanonymous** [bhattsameer/Bombers#78]
These SMS bombers are not working anymore
You can delete them from list
Their owners have left the project and has archived the repositories

13. | ni_bomber | Nikait 
14. | YetAnotherSMSBomber | AvinashReddy3108

**Comment by bhattsameer** [comment]
Thanks for update. Will do the needful.

**Comment by nithin644** [comment]
Bro sms was not coming please check it

**Comment by bhattsameer** [comment]
@anubhavanonymous I have changed the status of this two bomber scripts to Not-Working. I am not removing them as the repo is still available hence someone can learn using those repo code that how can we build a script for SMS bombing and so on. Thanks again.

@nithin644 Thanks for your comment, It would be helpful if you can provide name of the tool or script which is not working? I will mark it not working accordingly. Thanks.
