### ISSUE TITLE
Something is wrong please Re-run this script

### ISSUE THREAD

**Issue by Cottonwoodhill** [bhattsameer/Bombers#98]
Hi,
Could somebody please tell what I am doing wrong?
Thanks

**Comment by Cottonwoodhill** [comment]
Hi again, would you please support I would be glad to test your scrypt. Thanks and regards.

**Comment by Cottonwoodhill** [comment]
After correcting the time now the scrypt doesn't show any errors but no SMS are not sent.
This scrypt doens't work.

**Comment by Cottonwoodhill** [comment]
frozen here :
![Capture](https://user-images.githubusercontent.com/37047745/157258013-4025f33c-0797-4947-a014-e02441ef2b79.JPG)

**Comment by Cottonwoodhill** [comment]
https://github.com/bhattsameer/Bombers/issues/100

**Comment by Cottonwoodhill** [comment]
@peterphji
@bhattsameer
@IceWreck
@Yassinxm

**Comment by bhattsameer** [comment]
Hello @Cottonwoodhill, That script will only work for indian numbers if you are running initial one.
